config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :hotels do
    resources :rooms
  end

  resources :users do
    resources :bookings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :rooms
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :bookings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
    before_action :hotel_find, only: %i[show edit update destroy]

  def index
    @hotels = Hotel.all
  end

  def show
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      redirect_to hotel_path(@hotel)
    else
      render :edit
    end
  end

  def edit
  end

  def update
    if @hotel.update(hotel_params)
      redirect_to hotel_path(@hotel)
    else
      render :edit
    end
  end

  def destroy
    @hotel.destroy

    redirect_to hotels_path
  end

  private

  def hotel_params
    params.require(:hotel).permit(:name, :address, :rating)
  end

  def hotel_find
    @hotel = Hotel.find(params[:id])
  end

  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hotels/index.html.erb
<h1>All hotels</h1>

<ul>
  <% @hotels.each do |hotel| %>
    <li><%= link_to hotel.name, hotel_url(hotel) %> <%= link_to "Edit", edit_hotel_url(hotel) %> <%= link_to "Delete", hotel_url(hotel),
                                                                                              method: :delete,
                                                                                              data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>


<%= link_to "Add a new hotel", new_hotel_url %>

app/views/hotels/new.html.erb
<div class="container">
  <h1>Add a new hotel</h1>
</div>

<div class="container">
  <%= simple_form_for @hotel do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :rating, as: :range, input_html:{ min: '0', max: '5', step: '0.5' } %>
    <%= f.submit %>
  <% end %>
</div>

app/views/hotels/show.html.erb
<h1><%= @hotel.name %></h1>
<p><%= @hotel.address %></p>
<p>Rating: <%= @hotel.rating %></p>


<h2>Available rooms:</h2>
  <% if @rooms %>
<ul>
  <% @rooms.each do | room | %>
    <li><%= link_to room.name, room_url(room) %></li>
  <% end %>
</ul>
  <% else %>
    <p>No rooms available</p>
  <% end %>

<h3><%= link_to "Add a new room", new_hotel_room_url(@hotel) %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookingclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to MyBooking clone</h1>

<%= link_to "Hotels", hotels_url %>